apt update
apt install gnupg -y

apt install default-mysql-client -y

cat << EOF > addUsers.sql
CREATE USER $O_USER IDENTIFIED BY "$O_PASS";
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO $O_USER;

CREATE USER $RO_USER IDENTIFIED BY "$RO_PASS";
GRANT SELECT ON ${DB_NAME}.* TO $RO_USER;

CREATE USER $RW_USER IDENTIFIED BY "$RW_PASS";
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO $RW_USER;

CREATE USER $DB_USER IDENTIFIED BY "$DB_PASS";
GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO $DB_USER;

EOF


mysql -h $FQDN -u "${SERVER_USERNAME}@${FQDN}" --password="$SERVER_PASSWORD" $DB_NAME < addUsers.sql