apt update
apt-get install postgresql-client -y

export PGPASSWORD=$SERVER_PASSWORD

cat << EOF > addUserPSQL.sql

CREATE ROLE $DB_USER WITH LOGIN PASSWORD '${DB_PASSWORD}';
grant all PRIVILEGES on database $DB_NAME TO $DB_USER;
ALTER ROLE $DB_USER WITH NOSUPERUSER INHERIT CREATEROLE CREATEDB LOGIN PASSWORD '$DB_PASSWORD';


CREATE ROLE $RO_USER WITH LOGIN PASSWORD '${RO_PASS}';
GRANT CONNECT ON DATABASE $DB_NAME TO $RO_USER;
GRANT USAGE ON SCHEMA public TO $RO_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO $RO_USER;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO $RO_USER;


CREATE ROLE $RW_USER WITH LOGIN PASSWORD '${RW_PASS}';
GRANT CONNECT ON DATABASE $DB_NAME TO $RW_USER;
GRANT USAGE ON SCHEMA public TO $RW_USER;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO $RW_USER;
GRANT SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA public TO $RW_USER;

CREATE ROLE $O_USER WITH LOGIN PASSWORD '${O_PASS}';
GRANT $O_USER to azdbadmin;
ALTER DATABASE $DB_NAME OWNER TO $O_USER;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME to $O_USER;

EOF


psql --host=$FQDN --username="${SERVER_USERNAME}@${FQDN}" -d $DB_NAME -f addUserPSQL.sql
